version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ang
    ports:
      - "5432:5432"
  server:
    build:
      context: ./ang-morning-server
      dockerfile: ../Dockerfile.server
    environment:
      - ORIGIN=http://server:3010
      - APP_ENV=development
      - PORT=3333
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=ang
      - KAKAO_CLIENT_ID=YOUR_KAKAO
      - KAKAO_CLIENT_SECRET=YOUR_KAKAO
      - KAKAO_REDIRECT_URI=http://localhost:3000/oauth/kakao
    ports:
      - "3333:3333"
    volumes:
      - ./ang-morning-server/cmd:/ang-morning-server/cmd
      - ./ang-morning-server/internal:/ang-morning-server/internal
    restart: always
    depends_on:
      - db